# Generated by Django 3.1 on 2020-08-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unitconstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='on_planet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planet'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='x',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='y',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
