# Generated by Django 3.1 on 2020-08-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200818_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='air_vs_air_percent',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='ground_vs_air_percent',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='ground_vs_ground_percent',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='long_range_attack_percent',
            field=models.IntegerField(default=200),
        ),
    ]
