# Generated by Django 3.1 on 2020-08-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200818_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='post_attack_order',
            field=models.IntegerField(choices=[(0, 'Station On Planet'), (1, 'Wait In System'), (2, 'Recall To Main')], default=2),
        ),
    ]
