# Generated by Django 3.1 on 2020-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userstatus_post_attack_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='post_attack_order',
            field=models.IntegerField(choices=[(0, 'Attack Planet'), (1, 'Station On Planet'), (2, 'Move To System')], default=0),
        ),
    ]
