# Generated by Django 3.1 on 2020-08-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fleet_post_attack_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='post_attack_order',
            new_name='command_order',
        ),
    ]
