# Generated by Django 3.1 on 2020-08-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200818_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy_size', models.IntegerField(default=100)),
            ],
        ),
    ]
