# Generated by Django 3.1 on 2020-12-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fleet_ticks_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('numplayers', models.IntegerField(default=0)),
                ('planets', models.IntegerField(default=0)),
                ('artefacts', models.IntegerField(default=0)),
                ('taxation', models.FloatField(default=0.0)),
                ('networth', models.BigIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=30)),
                ('name_with_id', models.CharField(default='', max_length=35)),
                ('password', models.CharField(blank=True, default='', max_length=30)),
                ('fund_energy', models.IntegerField(default=0)),
                ('fund_minerals', models.IntegerField(default=0)),
                ('fund_crystals', models.IntegerField(default=0)),
                ('fund_ectrolium', models.IntegerField(default=0)),
                ('pm_message', models.CharField(default='', max_length=300)),
                ('relations_message', models.CharField(default='No relations message.', max_length=300)),
                ('empire_image', models.ImageField(blank=True, upload_to='empire_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('date_and_time', models.DateTimeField(blank=True)),
                ('user1_deleted', models.BooleanField(default=False)),
                ('user2_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('AO', 'Alliance offered'), ('W', 'War declared'), ('A', 'Alliance'), ('NO', 'Non agression pact offered'), ('NC', 'Non agression pact cancelled'), ('PC', 'Permanent non agression pact cancelled'), ('N', 'Non agression pact')], max_length=2)),
                ('relation_length', models.IntegerField(blank=True, default=None, null=True)),
                ('relation_creation_tick', models.IntegerField(default=0)),
                ('relation_cancel_tick', models.IntegerField(default=0)),
                ('relation_remaining_time', models.IntegerField(default=0)),
                ('empire1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empire1', to='app.empire')),
                ('empire2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empire2', to='app.empire')),
            ],
        ),
        migrations.CreateModel(
            name='RoundStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy_size', models.IntegerField(default=100)),
                ('tick_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='RoundParams',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='empire_num',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='alloc_research_portals',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='empire_role',
            field=models.CharField(choices=[('PM', 'Prime Minister'), ('VM', 'Vice Minister'), ('P', ''), ('I', 'Independent')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='request_aid',
            field=models.CharField(choices=[('PM', 'Prime minister'), ('VM', 'Prime minister and vice ministers'), ('A', 'All players'), ('N', 'Nobody')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='research_percent_portals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='research_points_portals',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='voting_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userstatus'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_construction',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_culture',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_energy',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_military',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_operations',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_population',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='alloc_research_tech',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterModelTable(
            name='planet',
            table='PLANET',
        ),
        migrations.AddField(
            model_name='messages',
            name='user1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to='app.userstatus'),
        ),
        migrations.AddField(
            model_name='messages',
            name='user2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to='app.userstatus'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='empire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empire'),
        ),
    ]
