# Generated by Django 3.1 on 2020-12-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201229_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(blank=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='roundstatus',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='agent_readiness',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='fleet_readiness',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='num_planets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='psychic_readiness',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='race',
            field=models.CharField(blank=True, choices=[('HK', 'Harks'), ('MT', 'Manticarias'), ('FH', 'Foohons'), ('SB', 'Spacebornes'), ('DW', 'Dreamweavers'), ('WK', 'Wookiees')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_buildings',
            field=models.IntegerField(default=220),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_cities',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_crystal_labs',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_mineral_plants',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_refinement_stations',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_solar_collectors',
            field=models.IntegerField(default=100),
        ),
    ]
