# Generated by Django 3.1 on 2021-01-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210113_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='agent_readiness_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='fleet_readiness_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='psychic_readiness_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='command_order',
            field=models.IntegerField(choices=[(0, 'Attack Planet'), (1, 'Station On Planet'), (2, 'Move To System'), (3, 'Merge In System'), (4, 'Merge In System A'), (5, 'Join Main Fleet'), (10, 'Explore Planet')], default=0),
        ),
    ]
