# Generated by Django 3.1 on 2021-01-23 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20210121_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(choices=[('SA', 'Successfull Attack'), ('UA', 'Unsuccessfull Attack'), ('SD', 'Successfull Defence'), ('UD', 'Unsuccessfull Defence'), ('SE', 'Successfull Exploration'), ('UE', 'Unsuccessfull Exploration'), ('SO', 'Successfull Specop Attack'), ('UO', 'Unsuccessfull Specop Attack'), ('DS', 'Successfull Specop Defence'), ('DU', 'Unsuccessfull Specop Defence'), ('SI', 'Sent aid'), ('RA', 'Requested aid'), ('M', 'Market operation'), ('N', 'None'), ('BB', 'Buildings Built'), ('UB', 'Units Built'), ('MR', 'Message Reseived'), ('RC', 'Relation Changed'), ('FM', 'Fleet Merged'), ('FJ', 'Fleet Joined Main'), ('E', 'Something Extra')], default='N', max_length=2)),
                ('tick_number', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('fleet1', models.TextField()),
                ('fleet2', models.TextField()),
                ('extra_info', models.TextField()),
                ('empire1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empire11', to='app.empire')),
                ('empire2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empire22', to='app.empire')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planet')),
                ('user1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user11', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user22', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
