# Generated by Django 3.1 on 2021-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_empire_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_personal_news',
            field=models.BooleanField(default=False),
        ),
    ]
