# Generated by Django 3.1 on 2021-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210124_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='extra_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='fleet1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='fleet2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
