# Generated by Django 3.1 on 2021-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210124_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='construction_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='economy_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='mail_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='military_flag',
            field=models.IntegerField(default=0),
        ),
    ]
