# Generated by Django 3.1 on 2021-01-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210124_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('SA', 'Successfull Attack'), ('UA', 'Unsuccessfull Attack'), ('SD', 'Successfull Defence'), ('UD', 'Unsuccessfull Defence'), ('SE', 'Successfull Exploration'), ('UE', 'Unsuccessfull Exploration'), ('SO', 'Successfull Specop Attack'), ('UO', 'Unsuccessfull Specop Attack'), ('DS', 'Successfull Specop Defence'), ('DU', 'Unsuccessfull Specop Defence'), ('SI', 'Sent aid'), ('RA', 'Requested aid'), ('M', 'Market operation'), ('N', 'None'), ('BB', 'Buildings Built'), ('UB', 'Units Built'), ('MS', 'Message Sent'), ('MR', 'Message Reseived'), ('RC', 'Relation Changed'), ('FM', 'Fleet Merged'), ('FJ', 'Fleet Joined Main'), ('E', 'Something Extra')], default='N', max_length=2),
        ),
    ]
