# Generated by Django 3.1 on 2021-01-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210124_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='planet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planet'),
        ),
    ]
