# Generated by Django 3.1 on 2021-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210124_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
