# Generated by Django 3.1 on 2021-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210125_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='ectrolium_decay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='mineral_decay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='agent',
            field=models.BigIntegerField(default=0, verbose_name='Agents'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='bomber',
            field=models.BigIntegerField(default=0, verbose_name='Bombers'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='carrier',
            field=models.BigIntegerField(default=0, verbose_name='Carriers'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='cruiser',
            field=models.BigIntegerField(default=0, verbose_name='Cruisers'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='droid',
            field=models.BigIntegerField(default=0, verbose_name='Droids'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='exploration',
            field=models.BigIntegerField(default=0, verbose_name='Exploration Ships'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fighter',
            field=models.BigIntegerField(default=0, verbose_name='Fighters'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='ghost',
            field=models.BigIntegerField(default=0, verbose_name='Ghost Ships'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='goliath',
            field=models.BigIntegerField(default=0, verbose_name='Goliaths'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='phantom',
            field=models.BigIntegerField(default=0, verbose_name='Phantoms'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='soldier',
            field=models.BigIntegerField(default=0, verbose_name='Soldiers'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='transport',
            field=models.BigIntegerField(default=0, verbose_name='Transports'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='wizard',
            field=models.BigIntegerField(default=0, verbose_name='Psychics'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='buildings_upkeep',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='energy_decay',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='energy_income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='energy_interest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='energy_production',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='population',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='population_upkeep_reduction',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='units_upkeep',
            field=models.BigIntegerField(default=0),
        ),
    ]
