# Generated by Django 3.1 on 2021-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210314_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='command_order',
            field=models.IntegerField(choices=[(0, 'Attack Planet'), (1, 'Station On Planet'), (2, 'Move To System'), (3, 'Merge In System'), (4, 'Merge In System A'), (5, 'Join Main Fleet'), (6, 'Merge Success'), (10, 'Explore Planet')], default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='total_portals',
            field=models.IntegerField(default=1),
        ),
    ]
