# Generated by Django 3.1 on 2021-03-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0024_auto_20210322_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_setting', models.CharField(choices=[('UE', 'Unexplored planets'), ('PE', 'Planets of empire'), ('PF', 'Planets of faction '), ('YE', 'Your empire'), ('YR', 'Your portals'), ('YP', 'Your planets'), ('U', 'Unused')], default='U', max_length=2)),
                ('color_settings', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('O', 'Orange'), ('Y', 'Yellow'), ('I', 'Indigo'), ('V', 'Violet')], default='G', max_length=1)),
                ('empire', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empire')),
                ('faction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
