# Generated by Django 3.1 on 2021-04-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_scouting'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=30)),
                ('empire', models.CharField(max_length=35)),
                ('planets', models.IntegerField(default=0)),
                ('networth', models.BigIntegerField(default=0)),
                ('race', models.CharField(max_length=30)),
            ],
        ),
    ]
