# Generated by Django 3.1 on 2021-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_halloffame'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundstatus',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
    ]
