# Generated by Django 3.1 on 2021-04-06 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_roundstatus_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specop_type', models.CharField(choices=[('O', 'Agent operation'), ('S', 'Psychic spell'), ('G', 'Ghost incantation')], default='O', max_length=1)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('specop_strength', models.FloatField(default=0)),
                ('extra_effect', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ticks_left', models.IntegerField(default=0)),
                ('user_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Suser2', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suser1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
