# Generated by Django 3.1 on 2021-04-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210407_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='target_planet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='target', to='app.planet'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='on_planet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationed', to='app.planet'),
        ),
    ]
