# Generated by Django 3.1 on 2021-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_fleet_target_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='crystal_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='construction',
            name='ectrolium_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='construction',
            name='energy_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='construction',
            name='mineral_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitconstruction',
            name='crystal_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitconstruction',
            name='ectrolium_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitconstruction',
            name='energy_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitconstruction',
            name='mineral_cost',
            field=models.BigIntegerField(default=0),
        ),
    ]
