# Generated by Django 3.1 on 2021-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210416_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconstruction',
            name='unit_type',
            field=models.CharField(choices=[('bomber', 'Bombers'), ('fighter', 'Fighters'), ('transport', 'Transports'), ('cruiser', 'Cruisers'), ('carrier', 'Carriers'), ('soldier', 'Soldiers'), ('droid', 'Droids'), ('goliath', 'Goliaths'), ('phantom', 'Phantoms'), ('wizard', 'Psychics'), ('agent', 'Agents'), ('ghost', 'Ghost Ships'), ('exploration', 'Exploration Ships')], max_length=11),
        ),
    ]
