# Generated by Django 3.1 on 2021-04-18 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210416_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='specops',
            name='planet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planet'),
        ),
        migrations.AddField(
            model_name='specops',
            name='specop_strength2',
            field=models.FloatField(default=0),
        ),
    ]
