# Generated by Django 3.1 on 2021-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_userstatus_energy_specop_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='specops',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
