# Generated by Django 3.1 on 2021-04-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_specops_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empire',
            name='artefacts',
        ),
        migrations.CreateModel(
            name='Artefacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('effect1', models.IntegerField(default=0)),
                ('effect2', models.IntegerField(default=0)),
                ('effect3', models.IntegerField(default=0)),
                ('ticks_left', models.IntegerField(default=0)),
                ('extra_effect', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date_and_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('empire_holding', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='artiempire', to='app.empire')),
                ('on_planet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planet')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='artefact',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.artefacts'),
        ),
    ]
