# Generated by Django 3.1 on 2021-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210420_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='empire',
            name='artefacts',
            field=models.ManyToManyField(related_name='empire_artefacts', to='app.Artefacts'),
        ),
    ]
