# Generated by Django 3.1 on 2021-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210420_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacts',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
